language:
  python
python:
  - '3.7.4'
install:
  - pip install -r requirements.txt
script:
  - cd gateway/back
  - coverage run manage.py test
  - cd ../../user
  - coverage run manage.py test
  - cd ../order
  - coverage run manage.py test
  - cd ../the_property
  - coverage run manage.py test