# Generated by Django 2.2.1 on 2019-10-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='addres',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
