# Generated by Django 2.2.1 on 2019-11-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191015_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='area',
            field=models.PositiveIntegerField(),
        ),
    ]
